export const useRecipes = () => [
  {
    id: 1,
    title: "Avocado Toast with Egg",
    description:
      "A quick, nutritious breakfast with crispy toast, creamy avocado, and a soft-boiled egg.",
    category: "Breakfast",
    time: "10 min",
    difficulty: "Easy",
    servings: "1 serve",
    caloriesPer100gr: 180,
    vegetarian: true,
    budgetFriendly: false,
    ingredients: [
      { name: "Bread slice", quantity: "1 slice" },
      { name: "Avocado", quantity: "50 g" },
      { name: "Egg", quantity: "1" },
      { name: "Salt", quantity: "to taste" },
      { name: "Pepper", quantity: "to taste" },
    ],
    steps: [
      "Toast the bread slice.",
      "Mash avocado and spread on toast.",
      "Boil the egg to desired doneness and place on top.",
      "Season with salt and pepper.",
    ],
    tags: ["quick", "vegetarian"],
    image: "/recipes/avocado-toast.jpg",
  },
  {
    id: 2,
    title: "Creamy Tomato Pasta",
    description:
      "Delicious and comforting pasta with a creamy tomato sauce, perfect for lunch.",
    category: "Lunch",
    time: "25 min",
    difficulty: "Medium",
    servings: "2 serves",
    servings: "2 serves",
    caloriesPer100gr: 150,
    vegetarian: true,
    budgetFriendly: true,
    ingredients: [
      { name: "Pasta", quantity: "200 g" },
      { name: "Tomato sauce", quantity: "150 ml" },
      { name: "Cream", quantity: "50 ml" },
      { name: "Olive oil", quantity: "1 tbsp" },
      { name: "Garlic", quantity: "1 clove" },
      { name: "Salt", quantity: "to taste" },
      { name: "Pepper", quantity: "to taste" },
      { name: "Parmesan cheese", quantity: "20 g (optional)" },
    ],
    steps: [
      "Boil pasta according to package instructions.",
      "Heat olive oil in a pan and sauté garlic until fragrant.",
      "Add tomato sauce and cream, simmer for 5 minutes.",
      "Mix pasta with the sauce and cook for another 2 minutes.",
      "Season with salt and pepper, serve with Parmesan if desired.",
    ],
    image: "/recipes/tomato-pasta.png",
    tags: ["quick", "budget", "lowcalorie", "vegetarian"],
  },
  {
    id: 3,
    title: "Grilled Chicken Salad",
    description:
      "Healthy salad with grilled chicken, fresh greens, and a light vinaigrette.",
    category: "Lunch",
    time: "20 min",
    difficulty: "Easy",
    servings: "2 serves",
    caloriesPer100gr: 120,
    vegetarian: false,
    budgetFriendly: false,
    ingredients: [
      { name: "Chicken breast", quantity: "200 g" },
      { name: "Lettuce", quantity: "100 g" },
      { name: "Cherry tomatoes", quantity: "50 g" },
      { name: "Olive oil", quantity: "1 tbsp" },
      { name: "Lemon juice", quantity: "1 tbsp" },
      { name: "Salt & pepper", quantity: "to taste" },
    ],
    steps: [
      "Grill chicken until fully cooked and slice.",
      "Mix lettuce and cherry tomatoes in a bowl.",
      "Add olive oil and lemon juice, season with salt and pepper.",
      "Top salad with grilled chicken slices.",
    ],
    image: "/recipes/chicken-salade.jpg",
    tags: ["quick", "budget", "lowcalorie"],
  },
  {
    id: 4,
    title: "Chocolate Chip Cookies",
    description:
      "Crispy on the edges and soft in the middle — perfect sweet treat.",
    category: "Desserts",
    time: "30 min",
    difficulty: "Medium",
    servings: "12 cookies",
    caloriesPer100gr: 450,
    vegetarian: true,
    budgetFriendly: true,
    ingredients: [
      { name: "Flour", quantity: "200 g" },
      { name: "Butter", quantity: "100 g" },
      { name: "Sugar", quantity: "100 g" },
      { name: "Chocolate chips", quantity: "100 g" },
      { name: "Egg", quantity: "1" },
      { name: "Vanilla extract", quantity: "1 tsp" },
    ],
    steps: [
      "Preheat oven to 180°C.",
      "Mix butter and sugar until creamy.",
      "Add egg and vanilla, then fold in flour and chocolate chips.",
      "Scoop onto baking tray and bake 12-15 min.",
    ],
    image: "/recipes/chocolate-cookies.png",
    tags: ["quick", "budget"],
  },
  {
    id: 5,
    title: "Vegetable Stir Fry",
    description:
      "Quick and colorful stir-fry with fresh vegetables and light soy sauce.",
    category: "Dinner",
    time: "15 min",
    difficulty: "Easy",
    servings: "2 serves",
    caloriesPer100gr: 90,
    vegetarian: true,
    budgetFriendly: true,
    ingredients: [
      { name: "Broccoli", quantity: "100 g" },
      { name: "Carrots", quantity: "50 g" },
      { name: "Bell peppers", quantity: "50 g" },
      { name: "Soy sauce", quantity: "1 tbsp" },
      { name: "Olive oil", quantity: "1 tsp" },
      { name: "Garlic", quantity: "1 clove" },
    ],
    steps: [
      "Heat oil in a pan and sauté garlic.",
      "Add vegetables and stir-fry for 5-7 min.",
      "Add soy sauce and cook for another 2 min.",
      "Serve immediately.",
    ],
    image: "/recipes/stir-fry.jpg",
    tags: ["quick", "lowcalorie", "vegan"],
  },
  {
    id: 6,
    title: "Chicken Caesar Salad",
    description:
      "Fresh romaine lettuce with grilled chicken, croutons, and light Caesar dressing.",
    category: "Lunch",
    time: "20 min",
    difficulty: "Easy",
    servings: "2 serves",
    caloriesPer100gr: 150,
    vegetarian: false,
    budgetFriendly: true,
    ingredients: [
      { name: "Romaine lettuce", quantity: "100 g" },
      { name: "Grilled chicken breast", quantity: "150 g" },
      { name: "Croutons", quantity: "30 g" },
      { name: "Parmesan", quantity: "20 g" },
      { name: "Caesar dressing", quantity: "2 tbsp" },
    ],
    steps: [
      "Chop the lettuce and place in a bowl.",
      "Slice the grilled chicken and add to the lettuce.",
      "Add croutons, parmesan, and dressing.",
      "Toss everything and serve immediately.",
    ],
    image: "/recipes/caesar.jpg",
    tags: ["quick", "budget"],
  },
  {
    id: 7,
    title: "Banana Oat Muffins",
    description:
      "Healthy and soft muffins made with ripe bananas and rolled oats.",
    category: "Desserts",
    time: "35 min",
    difficulty: "Easy",
    servings: "6 muffins",
    caloriesPer100gr: 220,
    vegetarian: true,
    budgetFriendly: true,
    ingredients: [
      { name: "Ripe bananas", quantity: "2" },
      { name: "Rolled oats", quantity: "100 g" },
      { name: "Egg", quantity: "1" },
      { name: "Honey", quantity: "2 tbsp" },
      { name: "Baking powder", quantity: "1 tsp" },
    ],
    steps: [
      "Preheat oven to 180°C.",
      "Mash bananas and mix with egg and honey.",
      "Add oats and baking powder, mix well.",
      "Pour batter into muffin tins and bake 20-25 min.",
      "Cool slightly and serve.",
    ],
    image: "/recipes/muffins.jpg",
    tags: ["budget", "vegetarian", "quick"],
  },
  {
    id: 8,
    title: "Grilled Salmon with Lemon",
    description:
      "Tender grilled salmon fillets with a hint of lemon and herbs.",
    category: "Dinner",
    time: "25 min",
    difficulty: "Medium",
    servings: "2 serves",
    caloriesPer100gr: 210,
    vegetarian: false,
    budgetFriendly: false,
    ingredients: [
      { name: "Salmon fillet", quantity: "200 g" },
      { name: "Olive oil", quantity: "1 tbsp" },
      { name: "Lemon", quantity: "1/2" },
      { name: "Salt", quantity: "to taste" },
      { name: "Pepper", quantity: "to taste" },
    ],
    steps: [
      "Preheat grill or oven to 200°C.",
      "Brush salmon with olive oil and season with salt and pepper.",
      "Grill for 10-12 min until cooked through.",
      "Squeeze lemon on top and serve.",
    ],
    image: "/recipes/salmon.png",
    tags: ["lowcalorie", "quick"],
  },
  {
  id: 9,
  title: "Overnight Oats with Berries",
  description: "A healthy and quick breakfast prepared the night before with oats and fresh berries.",
  category: "Breakfast",
  time: "5 min prep + overnight",
  difficulty: "Easy",
  servings: "1 serve",
  caloriesPer100gr: 120,
  vegetarian: true,
  budgetFriendly: true,
  ingredients: [
    { name: "Rolled oats", quantity: "50 g" },
    { name: "Milk or plant-based milk", quantity: "100 ml" },
    { name: "Berries", quantity: "50 g" },
    { name: "Honey", quantity: "1 tsp" }
  ],
  steps: [
    "Combine oats and milk in a jar or bowl.",
    "Add berries and honey.",
    "Cover and refrigerate overnight.",
    "Eat cold or warm in the morning."
  ],
  image: "/recipes/overnight-oats.jpg",
  tags: ["quick", "lowcalorie", "vegetarian"]
}
];
